steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    env:
      - 'ORGANIZATION_ID=$_ORGANIZATION_ID'
      - 'OPEN_API_KEY=$_OPEN_API_KEY'
      - 'API_KEY=$_API_KEY'

options:
  logging: NONE